server:
  port: 8080
spring:

  application:
    name: pf_contest
  datasource:
    url: jdbc:postgresql://sb-dev.cwuxhr16nyvh.ap-northeast-2.rds.amazonaws.com:5432/pf-contest?stringtype=unspecified
    username: nwrn
    password: nwrnadmin2019
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

cloud:
  aws:
    credentials:
      accessKey: AKIARF7TWOPSDZQ4UM52
      secretKey: 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
    region:
      static: ap-northeast-2

properties:
  awsBucketName: simgo123
  cloudfrontDomain: https://d1hds1xxjs6al7.cloudfront.net
  defaultImageUrl: https://d1hds1xxjs6al7.cloudfront.net/default.jpeg
  defaultProfileImageUrl: https://d1hds1xxjs6al7.cloudfront.net/default.jpeg
  tosspayments:
    secretKey: test_sk_nRQoOaPz8L9lyWZOpNG3y47BMw6v