server:
  port: 8080
spring:

  application:
    name: pf_contest
  datasource:
    url: jdbc:postgresql://sb-dev.cwuxhr16nyvh.ap-northeast-2.rds.amazonaws.com:5432/pf-contest?stringtype=unspecified
    username: nwrn
    password: nwrnadmin2019
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
